### ISSUE TITLE
This image format is not supported

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/xna-cncnet-client#23] opened 2016-12-08 18:56 UTC
https://forums.cncnet.org/index.php?topic=6959.0

07.12. 18:38:41.068    RMP: neo_dev!~4--YPOZnI@803ef594.1336ff0.34d758c5.IP4 NOTICE #cncnet-yr-game3597662,GO 75;5;10;0;3cef8cd2040c24ce639bbef4e7771fd5a2908909;Battle;619826563,
07.12. 18:38:41.075    Executing callback ​‭⁭‎⁯‎⁮‮‫‌‫⁭⁫‭​‪‍⁪‬​⁯⁮‮‏⁬‬‍⁮⁬⁫⁯⁬‭⁯‍‎‮⁫‎‎‮
07.12. 18:38:41.078    CnCNetGameLobby_CTCPReceived
07.12. 18:38:41.280    Message received: :Svenro_1__!~4--1qr0tw@gamesurge-d9fe8a3a.cm-7-3d.dynamic.ziggo.nl NOTICE #cncnet-yr-games :GAME R3;3.0.39;8;#cncnet-yr-game3031997;Svenro_1__'s Game;11000;Svenro_1__,wilinthegame;[2] Happy Trails;Battle;62.141.38.182;0

07.12. 18:38:41.285    RMP: Svenro_1__!~4--1qr0tw@gamesurge-d9fe8a3a.cm-7-3d.dynamic.ziggo.nl NOTICE #cncnet-yr-games,GAME R3;3.0.39;8;#cncnet-yr-game3031997;Svenro_1__'s Game;11000;Svenro_1__,wilinthegame;[2] Happy Trails;Battle;62.141.38.182;0,
07.12. 18:38:43.223    KABOOOOOOM!!! Info:
07.12. 18:38:43.225    Message: Exception has been thrown by the target of an invocation.
07.12. 18:38:43.237    Source: mscorlib
07.12. 18:38:43.239    TargetSite.Name: InvokeMethod
07.12. 18:38:43.240    Stacktrace:    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Rampastring.XNAUI.XNAControls.Callback.Invoke()
   at Rampastring.XNAUI.WindowManager.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.<>c.<.cctor>b__114_1(IUpdateable updateable, GameTime gameTime)
   at Microsoft.Xna.Framework.Game.SortingFilteringCollection`1.ForEachFilteredItem[TUserData](Action`2 action, TUserData userData)
   at Microsoft.Xna.Framework.Game.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at MonoGame.Framework.WinFormsGameWindow.RunLoop()
   at MonoGame.Framework.WinFormsGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at ‪‫‬⁭​‍​⁫‫‪‎⁪‭‍‏⁭‎⁯⁬‮‫‌‍⁭‫‫⁬‏⁭⁪⁫‫​‮‫‬‬‍‏‏‮.‬⁮‭⁯⁮‪‭‫‪‏⁯⁭‎⁭‮‮​‬‌⁮⁭⁪⁫⁭‭‮⁫‌‌‍‬‮‏‌‫⁮‌⁪‫⁬‮()
   at ⁭⁮‪⁫‬⁫‍⁭‫‮⁯‭⁯‫⁪‬⁪⁯‎​​‬‬‪⁭‍‮⁫‍⁪⁫‪‍‫‬⁪‫⁯⁬‬‮.‍‌‪⁬⁭‭‌‌‫⁬⁯⁯‌‭‬​‪⁯‬⁮‎‎⁪⁬‮⁭​​⁪⁭‪⁯⁬⁬‬‭⁮‎⁭‪‮(String[] )
   at ⁭‬⁮⁪‎‍​⁬‪‍‫⁮‌‫⁬‏‬‫⁭‎⁯⁮‮‫​‭‌⁮‪‪‎‌⁫⁭⁮‏⁪⁫‫⁬‮.‭⁯‏⁪‫⁯‍⁭⁪‍‮‮⁮‬⁭‮‭⁮‌‫‮‪⁮⁬‬‎‎‪‮⁬⁬⁭‫‭‪​‪‬⁭⁬‮(String[] )
07.12. 18:38:43.242    InnerException info:
07.12. 18:38:43.243    Message: This image format is not supported
07.12. 18:38:43.250    Stacktrace:    at Microsoft.Xna.Framework.Graphics.Texture2D.FromStream(GraphicsDevice graphicsDevice, Stream stream)
   at Rampastring.XNAUI.AssetLoader.LoadTextureUncached(String name)
   at ⁪⁫⁬‏‭‍‌‬‎⁬‭⁯⁭⁬‪‪‏⁮‪‬‎‍⁪‎⁭⁭⁮‍‬⁪⁯⁭⁫⁮‭⁯⁬⁪‎⁬‮.‬⁪​‭‫‎‍‪‎‪‌⁭⁯⁫⁮‎‍⁬‎‌⁬⁯‬‏‍⁯⁬‮⁮⁯⁫‫‮‎​⁪‌⁯⁭‮()
   at ‏‌‮‪‎​​⁮⁯⁪⁫‮‍⁫⁬‫​‍‫‬​⁮‏‌⁯​⁯⁭‍⁬​‭‍⁪‮‪‮‍‬‌‮.⁭‭‬‍‍⁮⁯‏⁭‏‏‬⁪⁭‪⁬⁭‬⁪⁫‫‍⁫⁪​⁫‏​‪‌‌‎‬‎‪‌‍⁬‮⁯‮()
   at ‏‌‮‪‎​​⁮⁯⁪⁫‮‍⁫⁬‫​‍‫‬​⁮‏‌⁯​⁯⁭‍⁬​‭‍⁪‮‪‮‍‬‌‮.‏⁬‫⁬⁬⁫⁫⁮⁯‏‬‬‮​⁮‫‍​⁬⁮⁭⁯‬⁮⁪⁫‎‮‭⁯‏‌‌‭⁬⁯‪‪‪‪‮(⁪⁫⁬‏‭‍‌‬‎⁬‭⁯⁭⁬‪‪‏⁮‪‬‎‍⁪‎⁭⁭⁮‍‬⁪⁯⁭⁫⁮‭⁯⁬⁪‎⁬‮ )
   at ‮‍​⁯‭⁭⁯‬⁭‮‏⁭‮⁯‬‏‬‬⁯‮​⁮⁬‎⁬⁯⁬⁬‌‏‫⁭‫‏‍​‏‭‌⁬‮.⁭⁫‏‪⁪‌⁬⁭‬‬⁪‌‎‮‎⁫‍‪‏​‎⁪‏‏‎⁫⁬⁯‎⁬​‮​‪‬‫‌‏‏⁭‮(‏‫​⁭‏⁪⁭⁬⁮⁯‌⁪​‏‫‬⁯⁫⁫⁬⁬⁬⁬⁯‏‭‭⁫‏⁭‌‪‪​‮⁮‬⁫‌⁮‮ , ⁪⁫⁬‏‭‍‌‬‎⁬‭⁯⁭⁬‪‪‏⁮‪‬‎‍⁪‎⁭⁭⁮‍‬⁪⁯⁭⁫⁮‭⁯⁬⁪‎⁬‮ )
   at ‌⁮⁭‬‏‍⁫‎⁫⁭⁫⁯‬⁬⁬⁮⁯‏⁪‏‭⁬‌⁭⁭‍⁪‬⁯‮‌‫⁮‏‬‍⁬​⁭‭‮.⁭⁫‏‪⁪‌⁬⁭‬‬⁪‌‎‮‎⁫‍‪‏​‎⁪‏‏‎⁫⁬⁯‎⁬​‮​‪‬‫‌‏‏⁭‮(‏‫​⁭‏⁪⁭⁬⁮⁯‌⁪​‏‫‬⁯⁫⁫⁬⁬⁬⁬⁯‏‭‭⁫‏⁭‌‪‪​‮⁮‬⁫‌⁮‮ , ⁪⁫⁬‏‭‍‌‬‎⁬‭⁯⁭⁬‪‪‏⁮‪‬‎‍⁪‎⁭⁭⁮‍‬⁪⁯⁭⁫⁮‭⁯⁬⁪‎⁬‮ )
   at ‍⁭‌‎‬‌‎⁫‭‍‭⁫‏‫⁫‏⁭‎‌‭‎‎‬⁫‌‍‪⁯‏⁭⁯‎‮‭⁭‏⁮‪⁭‭‮.⁬‍⁬‌‍‮‪‬​⁫‮⁫⁭‏​‭‍‌​‮⁮‎​⁪‍‪⁯‫‏‍‍⁫⁮⁫⁪⁬‌⁫‬‪‮(String , String )
   at ‌‮‫‏‮‏‪‏⁯⁮‏⁫‬‍⁫‪‏‮‎⁯⁬‬‭‫‪​‍‌⁭​‭⁪⁬‪​‌⁪⁭‭‮‮.⁭‬‫‭⁪‫‏⁮‮‬‍​‌⁭‭⁪‪‭‎⁬​⁪‪‎‌‍‏‎‫⁬‪‭⁮⁭‫‫⁪⁪‬‫‮(String , String )
   at ‍⁭‌‎‬‌‎⁫‭‍‭⁫‏‫⁫‏⁭‎‌‭‎‎‬⁫‌‍‪⁯‏⁭⁯‎‮‭⁭‏⁮‪⁭‭‮.‮⁯⁮⁭‬⁭⁯⁯‎‫‎⁮​⁭‪‎‪⁭​​⁪‭‍⁮⁮⁮‫‌‍‪‮‏‮‫‪​‌​​⁬‮(Object , ‬⁪‍⁫‌‮⁮⁪‍‪⁭⁪⁫‭⁯⁮⁫⁪⁪‭⁮⁯‫‌‬⁮⁯⁫‫‪⁫⁮‫‎⁮⁬​⁯‌⁪‮ )
   at ‫‏⁯‭⁪‮‭‮⁮‫‎‭⁯⁫⁮‎‪⁬⁪‏⁭‎‫‌⁪‌​‍‮⁮⁮‌​‌‮⁬⁯‫‌⁮‮.‏‮⁭‮​‎⁯‍⁬⁫⁫⁪‌‭‎‍‮⁭⁫‬‬‮‎‫‬⁮‎⁬‌‎⁭‮‬‍‍‭​‫‪⁮‮(String , String )
   at ⁮‭‭‮⁮‍‪⁬‬‏‍‭​‌‪⁯‎⁯​‏‭⁯‌​‬⁪⁬‮⁪‬⁯‭‬‭⁫‬‫⁫‭‍‮.​‭⁭‎⁯‎⁮‮‫‌‫⁭⁫‭​‪‍⁪‬​⁯⁮‮‏⁬‬‍⁮⁬⁫⁯⁬‭⁯‍‎‮⁫‎‎‮(String , String , String )

**Comment by Rampastring** [comment] 2016-12-08 21:51
Fixed already in https://github.com/CnCNet/xna-cncnet-client/commit/f1e09f3809e3e36b6470ed289e82d470e4309354

**Comment by GrantBartlett** [comment] 2016-12-08 22:53
Great OK I'll close this then, because that was pushed last night and the bug was reported before the newest update.

**Comment by GrantBartlett** [comment] 2016-12-10 12:01
This happens when loading a custom map it appears. 

10.12. 11:53:17.730    Loading custom map C:\Users\Home\Documents\Visual Studio 2015\Projects\!yr-theme\cncnet-yr-client-theme\Maps\Custom\19c2bbabde5bf1e81c535143b361dd6d15975809.map failed!
10.12. 11:53:17.803    KABOOOOOOM!!! Info:
10.12. 11:53:17.807    Message: This image format is not supported
10.12. 11:53:17.813    Source: MonoGame.Framework
10.12. 11:53:17.818    TargetSite.Name: FromStream
10.12. 11:53:17.823    Stacktrace:    at Microsoft.Xna.Framework.Graphics.Texture2D.FromStream(GraphicsDevice graphicsDevice, Stream stream)
   at Rampastring.XNAUI.AssetLoader.TextureFromImage(Image image)
   at ClientCore.CnCNet5.GameCollection.Initialize(GraphicsDevice gd)
   at ‌​‪​‪‌‫‭‪⁭‪‭‬⁪​⁬‌‍‪⁫‏⁭‬‌‪⁭‍‌‫⁫‫‎‍‌⁮‏‮‫‬‎‮.‫‫⁮⁭​‌‍⁮‌‏‍⁯‏⁫⁪‪‮‬⁮⁮⁮‫‍⁫‭⁯⁬‍‎‬⁫‬⁫‎‪‮‮‏‏‏‮(GameCollection , GraphicsDevice )
   at ‌​‪​‪‌‫‭‪⁭‪‭‬⁪​⁬‌‍‪⁫‏⁭‬‌‪⁭‍‌‫⁫‫‎‍‌⁮‏‮‫‬‎‮.⁫⁫‎⁪‫‫⁮⁯‮‏‮‭​⁬​‌‎‎‎⁮⁯‍‍‪‪‌⁪⁫‌⁭‭‫⁭‌⁮‬⁯‮⁭⁮‮()
   at ‌​‪​‪‌‫‭‪⁭‪‭‬⁪​⁬‌‍‪⁫‏⁭‬‌‪⁭‍‌‫⁫‫‎‍‌⁮‏‮‫‬‎‮.⁯⁭‌‎‭⁫‪⁮‏‎‎​⁪‭‏⁫‮⁫‍​‭⁫‭⁪‪‭⁭⁬‎‏‫​‍‎‏‍‏⁯‬⁬‮()
   at ‌​‪​‪‌‫‭‪⁭‪‭‬⁪​⁬‌‍‪⁫‏⁭‬‌‪⁭‍‌‫⁫‫‎‍‌⁮‏‮‫‬‎‮.‌‫⁯‫‪​‏‮⁯‫⁯‍⁫‌‮⁪⁫​‌‬‪‭⁭‏‮⁭‭⁭‭‌‏‍⁫⁯‫‭⁪⁪‎⁪‮(GameTime )
   at Rampastring.XNAUI.WindowManager.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.<>c.<.cctor>b__114_1(IUpdateable updateable, GameTime gameTime)
   at Microsoft.Xna.Framework.Game.SortingFilteringCollection`1.ForEachFilteredItem[TUserData](Action`2 action, TUserData userData)
   at Microsoft.Xna.Framework.Game.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at MonoGame.Framework.WinFormsGameWindow.RunLoop()
   at MonoGame.Framework.WinFormsGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at ‌⁭‪⁪‎​‫‪⁫⁮‭⁭‭​‫‪‪‮⁯‎‪⁭‏⁬‮⁭⁪‌⁯‫‬‫‍⁭⁬⁬⁫​‪⁫‮.‎‪⁪‭⁭‬⁮‭‭⁯‏⁪‎⁯⁫‌‫‌‍‏⁮‫⁭⁬‬‍⁭‏‎⁮⁫‮‫‪⁬‪⁭‭‬‎‮()
   at ‮‪‬⁬‏‮‏‎⁫‍‏⁯⁯‏‭⁯⁬‮​⁪‎⁫‌‏‍‮⁯⁮​‫‬‪​‍⁭‌⁪⁭⁭‭‮.‫⁪‬⁫⁮⁪‬⁯⁫‬‏‭‌⁪‪‭‎‮‏‏​⁯⁬⁭‫‫‫‪‭‌‮⁯⁮‭⁭‎‍‌⁬⁪‮(String[] )
   at ‮⁬⁬⁭​​‫‍‭‮⁭‮‌‏⁮⁬‌​⁮‮⁬‍⁯‬⁯‎‬⁫‬‮⁯‌‮‮‏⁯‫‮‬‎‮.⁬‏‫⁭‪⁭‏‎‬‮‍⁮⁮‪⁯‌⁮‭‍⁬⁪‮‭⁭‭‭‪​⁫​​⁭‏⁬⁯⁫‮‪⁬‎‮(String[] )
10.12. 11:53:17.828    InnerException info:
10.12. 11:53:17.834    Message: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.

10.12. 11:53:17.839    Stacktrace:    at SharpDX.Result.CheckError()
   at SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
   at SharpDX.Direct3D11.Texture2D..ctor(Device device, Texture2DDescription description, DataRectangle[] data)
   at Microsoft.Xna.Framework.Graphics.Texture2D.CreateTex2DFromBitmap(BitmapSource bsource, GraphicsDevice device)
   at Microsoft.Xna.Framework.Graphics.Texture2D.PlatformFromStream(GraphicsDevice graphicsDevice, Stream stream)
   at Microsoft.Xna.Framework.Graphics.Texture2D.FromStream(GraphicsDevice graphicsDevice, Stream stream)


[19c2bbabde5bf1e81c535143b361dd6d15975809.txt](https://github.com/CnCNet/xna-cncnet-client/files/643721/19c2bbabde5bf1e81c535143b361dd6d15975809.txt)

**Comment by Rampastring** [comment] 2016-12-10 14:27
Doesn't happen to me. The inner exception error message would point to a problem with the graphics device rather than the image format, "The GPU device instance has been suspended."

I can add a check to Rampastring.XNAUI.AssetLoader.TextureFromImage(Image image) to check if the texture was loaded succesfully though.

**Comment by GrantBartlett** [comment] 2016-12-10 14:40
It happens to me on and off, which is strange.

**Comment by Rampastring** [comment] 2016-12-10 16:39
Implemented. It's not entirely without side-effects though, if loading a map preview during startup fails then the map will have a black preview or the starting location indicators will be shown in invalid locations.

https://github.com/CnCNet/xna-cncnet-client/commit/acaf7230b247d001c36654a85e873c1d0bf83164

**Comment by GrantBartlett** [comment] 2016-12-10 17:39
Better than a crash - thanks @Rampastring 

I was thinking, maybe the Loadup screen should say what it is actually loading, so it doesn't appear to be "slow". For instance, it could just be a simple text string saying:

"Loading maps - 1/20"  etc.

**Comment by GrantBartlett** [comment] 2017-01-24 18:43
24.01. 19:23:01.407    Stacktrace:    at Microsoft.Xna.Framework.Graphics.Texture2D.FromStream(GraphicsDevice graphicsDevice, Stream stream)
   at Rampastring.XNAUI.AssetLoader.LoadTexture(String name)
   at ⁫‭‬⁫⁫⁬⁯⁪‪‭‭‌⁯‌‬‌‫‏⁮⁯⁫​‌‌‎⁫⁭⁯‌‌‍‌⁫‏‍‍‍‮⁪‍‮.‫‎‪‍‭‬‪‎‪‌‮⁭⁬‭‍⁮‍⁮‍‏‎‫‫‭‮‪‌⁪‍⁮‭‭⁯⁪⁫‭‪⁮⁮⁫‮()
   at ⁫‭‬⁫⁫⁬⁯⁪‪‭‭‌⁯‌‬‌‫‏⁮⁯⁫​‌‌‎⁫⁭⁯‌‌‍‌⁫‏‍‍‍‮⁪‍‮.⁬‎⁬‌‭‌⁯‬‏‮‬⁪⁪⁭‌⁯‮‍‬⁬‪‫‪​‪⁯‌‏‏⁯‫‎‭‏‪⁮‌⁮⁯‮()
   at Microsoft.Xna.Framework.Game.DoInitialize()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at ‏‏⁪⁭‏‏‭‬‮⁬⁮​⁫‌‮‮‫⁪‫‌‎‪⁮‫⁬⁫‪⁭‫‭‫‏‭‪​‏‫⁪‫‏‮.‫⁬‪⁯⁪‎​⁪⁪⁭‍‬​⁮‏⁭‪‍⁫‫‭⁮‬‫‍‏‍‭⁪​⁪⁫⁬⁭​⁭​‍‏⁬‮()
   at ⁬⁬‭⁫‎⁭⁪‌‮​‍‍⁬‪‬‎⁯⁪‮‭‪‎⁫⁮‬⁯​‍‮‭‫‬⁪⁪‌‮‬‬⁮‬‮.‎‎‭⁬‮⁮‮⁭‮‪‍‪‍⁫⁪‏​⁪⁭‫‫‬‫‬‎​‮‮‌⁯‭⁭‏​‌⁫⁯⁫⁯‪‮(String[] )
   at ⁬‪‎⁪‬‏‭​⁪⁫⁫‏‍‪‌​‍‎‬⁫⁪⁪‪⁭⁪‪‭‬⁮‬⁮‎‎‌‭‬⁫‎‏⁬‮.‮⁭‮⁪‍‮⁪‌‪⁫‏‎⁭‏​⁭⁭⁫⁫⁮⁬‌‍‬⁭⁮⁪⁬‍⁮‌⁯⁮‏‎‎‏⁯⁯⁬‮(String[] )
24.01. 19:23:01.407    InnerException info:
24.01. 19:23:01.407    Message: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown
24.01. 19:23:01.407    Stacktrace:    at SharpDX.Result.CheckError()
   at SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
   at SharpDX.Direct3D11.Texture2D..ctor(Device device, Texture2DDescription description, DataRectangle[] data)
   at Microsoft.Xna.Framework.Graphics.Texture2D.CreateTex2DFromBitmap(BitmapSource bsource, GraphicsDevice device)
   at Microsoft.Xna.Framework.Graphics.Texture2D.PlatformFromStream(GraphicsDevice graphicsDevice, Stream stream)
   at Microsoft.Xna.Framework.Graphics.Texture2D.FromStream(GraphicsDevice graphicsDevice, Stream stream)

**Comment by Rampastring** [comment] 2017-01-28 20:00
The issue in the post appears to be solved.

I also think this is a duplicate of #27.

**Closed by Rampastring** 2017-01-28 20:00 UTC
