### ISSUE TITLE
Unable to load DLL d3d11.dll The specfied module could not be found.

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/xna-cncnet-client#4] opened 2016-12-03 09:28 UTC
Unable to load DLL d3d11.dll The specfied module could not be found.

https://forums.cncnet.org/index.php?topic=6881.0

**Comment by Rampastring** [comment] 2016-12-03 10:17
They're most likely running an out-of-date version of Windows Vista. Vista needs Service Pack 2 and Platform Update for DirectX11, which the client depends on.

**Comment by GrantBartlett** [comment] 2016-12-03 12:11
https://forums.cncnet.org/index.php?topic=6881.msg49939#msg49939

Windows Vista Business SP-2. Asking about directx11 now

**Comment by Rampastring** [comment] 2016-12-03 15:16
DX11 is included with the "Platform Update" for Vista.

**Comment by Rampastring** [comment] 2016-12-05 22:15
Basically a duplicate of https://github.com/CnCNet/xna-cncnet-client/issues/10

**Closed by Rampastring** 2016-12-05 22:16 UTC
